### ISSUE TITLE
Useless kuio usage ?

### ISSUE THREAD

**Issue by Cpasjuste** [Rinnegatamante/AutoBoot#1]
Hi Rinnegatamante, 

I think using kuio for reading in ux0:data is useless :)

**Comment by Rinnegatamante** [comment]
In this specific case, you could be correct since on module_start we still have access to SD card. (At least on standard apps, didn't check if the same applies for SceShell too). I'll perform some tests without kuio btw.

**Comment by Cpasjuste** [comment]
I think we always have read access to us from anywhere in user modules.

**Comment by Cpasjuste** [comment]
to us = to ux0

**Comment by Rinnegatamante** [comment]
Definitely not, write an user plugin that tries to read stuffs inside a sceDisplaySetFrameBuf hook for example without kuio and launch it on a retail game/maidump backup. It will fail due to SD not being accessible.

**Comment by Rinnegatamante** [comment]
Seems like SceShell is like all other apps. kuio dependency removed with https://github.com/Rinnegatamante/AutoBoot/commit/ab79b79cd3fb9818708f3b965e44e4984af47ce8
