### ISSUE TITLE
Check the existence of the titleid app before launching it

### ISSUE THREAD

**Issue by alpakeno** [Rinnegatamante/AutoBoot#2]
char titleid_path[128];
sprintf(titleid_path, "ux0:/app/%s/eboot.bin", titleid);	
fd = sceIoOpen(titleid_path, SCE_O_RDONLY, 0777);
if (fd >= 0){
	launchAppByTitleid(titleid);
}	

Is it possible?

**Comment by Rinnegatamante** [comment]
Not every app is installed under ux0 (ex. somesystem apps are under vs0). A proper app existence check would require to integrate sqlite in a plugin and probably it wouldn't work. SceSqlite could solve the issue but is unusable due to sqlite3_temp_directory not being accessible.

**Comment by alpakeno** [comment]
So how about check 2 times, one for ux0: and the other for vs0: ( the two share the same /app/eboot.bin path.

**Comment by CelesteBlue-dev** [comment]
because there is also gro0, pd0, ux0:pspemu.
too much for nothing...
