### ISSUE TITLE
AutoBoot puts vita in a bootloop

### ISSUE THREAD

**Issue by iWockstar** [Rinnegatamante/AutoBoot#6]
AutoBoot is 100% the best plugin on the Vita now that we have so many great launchers. Because of this, I tried to reinstall it, but somethings up with it’s compatibility or the way you have to install it on 3.65. It always puts my console in a boot loop and im doing everything exactly how you explained (the data folder, the tai file, and the config text) at least seven times. It could be conflicting with something and if so I’ll get rid of it asap. I want to use AutoBoot so badly, do you have any suggestions? Thanks!

**Comment by Rinnegatamante** [comment]
What plugins do you have installed? Also how did you install Henkaku on first place? (eg: through webkit explit, using MLThaku, etc)

**Comment by iWockstar** [comment]
@Rinnegatamante The plugins I have are 0syscall6 by SKGleba, Adrenaline by TheOfficial Floe (Fix double touch), ftpeverywhere, NoNpDrm by TheOfficial Flow, NoPowerLimits by Electry, NoPsmDrm by frangarcj, NoPspEmuDrm by SilicaAndPina, PSVShellPlus by GrapheneCt, Quick Menu Plus by cuevavirus,reAuth - Use PlayStation store and sign-in by curvavirus, rematch by dots-tb, Vitacheat by FinalCheat, VitaGrafox by Electry,vbanim by SKGleba, YAMT by SKGleba, Vita Nearest Neighbbour by MuxaJlBl4,taihen by yifanlu, PSVita StorageMgr by CelesteBlue-Dev, itls enso by SKGleba, ioplus by CelesteBlue-Dev, InfiniteNet by you, and Henkaku by Henkaku. They all function together at this time if that helps.

EDIT: If it's helpful I have libshacccg.suprx in my data folder too. Nothing for it in tai though.

The way I modded my vita is with the Henlo method on the Vita hacks guide. I believe I started with a vita at 3.74 and downgraded to 3.65 when the guide told me to. Thanks!

**Comment by iWockstar** [comment]
So the website it made me go to on my vita in order to install Henkaku was http://jailbreak.psp2.dev. I have the permanent itls enso 3.65 mod.

**Comment by Rinnegatamante** [comment]
Try using this suprx.
[AutoBoot.zip](https://github.com/Rinnegatamante/AutoBoot/files/11948038/AutoBoot.zip)

**Comment by iWockstar** [comment]
Ur the goat! I'm on my way home right now, and I'll give it a try and let you know how it goes. Thanks so much!

**Comment by iWockstar** [comment]
Hello, sorry it took a while to get back to you. Whenever I reset plugins, I have to reorganize all my games and everything, but I did try the new suprx with multiple apps, and it still seems to put me in a boot loop for some reason. If you feel like somethings wrong with my specific PS Vita and maybe I just shouldn't use Auto Boot let me know. Thanks!

**Comment by Rinnegatamante** [comment]
I personally never tried it on 3.65 fw but quite sure nids of the used funcs should be same. (I test stuffs mostly on 3.60 fw)

**Comment by iWockstar** [comment]
I'd assume the same, which leads me to think theres something up with my Vita. I don't really see many, if any, other people saying they're experiencing the same issue
