### ISSUE TITLE
"Startup category" setting crash

### ISSUE THREAD

**Issue by Maxximo88** [Rinnegatamante/AutoBoot#8]
Error when you follow this:
Start --> Categories --> Change Startup Category after "Recently Played"
"An error occurred:
[String "?"]:1403: attempt to index a nil value

I would like to set "All" as default.

PS: in addition, please add Autoboot app to VitaDB!

**Comment by Rinnegatamante** [comment]
I've no idea what are you talking about. This is a plugin and is not made in Lua like what you reported suggests.
